"""Agregar columna de Rol

Revision ID: 0da96ca79b9c
Revises: 625b0b561b04
Create Date: 2026-04-10 10:56:56.359884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da96ca79b9c'
down_revision = '625b0b561b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=50), server_default='Usuario', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
